sudo: required
language: node_js

node_js:
  - '4.4'

services:
  - docker

install:
  - npm install --loglevel=silent

script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm cache clean
  - npm run lint
  - npm run build
  - npm test

env:
  - DOCKER_IMAGE_NAME=swaggerapi/swagger-editor

deploy:
  on:
    tags: true
  provider: npm
  email: "apiteam@swagger.io"
  api_key:
    secure: G/bZcCrTPWYcLRrmFGMTxrNw6dOJkvijpjwprDieGarhwhY9Y2EZlzFIuLIKxE7Aht9W5P61Ic7tI48Akeb68GGtTDXTlut/BC6tDG0q5yXh9MoEerqrYmgd1KErT/szAQX+kdFAY+NDM9rov8o6H+iFNZBYvxf11dBBFoXv11Q=
