name: build-login-push
description: Builds an image, logs in to a docker registry, and pushes the image to it.
inputs:
  - { name: DOCKER_PASSWORD, description: Password for docker registry, isSecret: true}
  - { name: DOCKER_USERNAME, description: Username for docker registry, isSecret: true}
  - { name: IMAGE_REF, description: 'Docker image reference (regex: `((registry/)?namespace/)?repo(:tag)?`)' }
  - { name: BUILD_CONTEXT, type: dir }
run:
  serial:
    - op: build
      args: [ BUILD_CONTEXT, IMAGE_REF ]
    - op: login
      args: [ DOCKER_PASSWORD, DOCKER_USERNAME ]
      results: [ DOCKER_CONFIG ]
    - op: push
      args: [ DOCKER_CONFIG, IMAGE_REF ]
