name: login
description: Logs in to a docker registry
inputs:
  - { name: DOCKER_PASSWORD, description: Password for docker registry, isSecret: true}
  - { name: DOCKER_USERNAME, description: Username for docker registry, isSecret: true}
  - { name: DOCKER_CONFIG, description: Existing config to add login to; by default a new config is generated, isSecret: true, type: file}
outputs:
  - { name: DOCKER_CONFIG, description: Can be used for caching, , isSecret: true, type: file}
run:
  container:
    image: docker:1.12.0
    cmd: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    envVars:
      - name: DOCKER_PASSWORD
      - name: DOCKER_USERNAME
    mounts:
    - name: DOCKER_CONFIG
      path: /root/.docker/config.json
